/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.3/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
  	id("com.energizedwork.heroku-buildpack-runnable-jar") version "1.3"
  	id("com.github.johnrengelman.shadow") version "7.1.2"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

tasks.jar {
  manifest {
	archiveBaseName.set("dofusbuilderapi")
    attributes["Main-Class"] = "github.souchy.ankama.quickfus.Quickfus"
  }
}

herokuRunnableJarBuildpack {
    // artifactUrl = "https://example.com/my-runnable-jar.jar"
    applicationName = "quickfus-backend"
	// gitUrl = "https://git.heroku.com/quickfus-backend.git"
    apiKey = "ae9ebe3e-6c82-4b52-8bb9-517a59a41986"
	// artifactFile = file(File("build/libs/DofusBuilder Backend-all.jar"))
	artifactFile = file(File("../Quickfus.jar"))
	procfileContents = "web: java -jar application.jar"
	javaVersion = "17"
}

sourceSets {
    main {
        resources {
            srcDirs("../DofusBuilder Frontend/src/res/i18n")
            srcDirs("../DofusBuilder Frontend/src/res/items0")
        }
    }
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.7.2")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:30.1.1-jre")


    implementation("io.netty:netty-all:4.1.78.Final")
	implementation("com.google.code.gson:gson:2.9.1")
    implementation("org.reflections:reflections:0.10.2")
    implementation("org.slf4j:slf4j-simple:latest.release")
	
	implementation("org.json:json:20220320")
	
    // implementation("org.mongodb:mongodb-driver-reactivestreams:4.6.0")
	implementation("org.mongodb:mongodb-driver-core:4.7.1")
    implementation("org.mongodb:mongodb-driver-sync:4.7.1")
	implementation("org.mongodb:mongodb-driver-reactivestreams:4.7.1")
	implementation("org.mongodb:bson:4.7.1")

	// jersey + netty
	implementation("org.glassfish.jersey.connectors:jersey-netty-connector:3.1.0-M7")
	implementation("org.glassfish.jersey.containers:jersey-container-netty-http:3.1.0-M7")

	implementation("org.glassfish.jersey.inject:jersey-hk2:3.1.0-M7")
	implementation("org.glassfish.jersey.media:jersey-media-json-binding:3.1.0-M7")

	// https://mvnrepository.com/artifact/jakarta.activation/jakarta.activation-api
	implementation("jakarta.activation:jakarta.activation-api:2.1.0")
	
	// https://mvnrepository.com/artifact/org.eclipse.jetty/jetty-server
	implementation("org.eclipse.jetty:jetty-server:11.0.11")
	implementation("org.eclipse.jetty:jetty-webapp:11.0.11")
	implementation("org.glassfish.jersey.containers:jersey-container-jetty-http:3.1.0-M7")

	// https://mvnrepository.com/artifact/com.sun.jersey/jersey-servlet
	// implementation("com.sun.jersey:jersey-servlet:1.19.4")
	// https://mvnrepository.com/artifact/org.glassfish.jersey.containers/jersey-container-servlet
	implementation("org.glassfish.jersey.containers:jersey-container-servlet:3.1.0-M7")

}

application {
    // Define the main class for the application.
    mainClass.set("github.souchy.ankama.quickfus.Quickfus")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
