/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.3/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

tasks.jar {
  manifest {
	archiveBaseName.set("dofusbuilderapi")
  }
}

sourceSets {
    main {
        resources {
            srcDirs("../DofusBuilder Frontend/src/res/i18n")
            srcDirs("../DofusBuilder Frontend/src/res/items0")
        }
    }
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.7.2")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:30.1.1-jre")


    implementation("io.netty:netty-all:4.1.78.Final")
	implementation("com.google.code.gson:gson:2.9.1")
    implementation("org.reflections:reflections:0.10.2")
    implementation("org.slf4j:slf4j-simple:latest.release")
	
	implementation("org.json:json:20220320")
	
    // implementation("org.mongodb:mongodb-driver-reactivestreams:4.6.0")
	implementation("org.mongodb:mongodb-driver-core:4.7.1")
    implementation("org.mongodb:mongodb-driver-sync:4.7.1")
	implementation("org.mongodb:mongodb-driver-reactivestreams:4.7.1")
	implementation("org.mongodb:bson:4.7.1")

	// jersey + netty
	implementation("org.glassfish.jersey.connectors:jersey-netty-connector:3.1.0-M7")
	implementation("org.glassfish.jersey.containers:jersey-container-netty-http:3.1.0-M7")

	implementation("org.glassfish.jersey.inject:jersey-hk2:3.1.0-M7")
	implementation("org.glassfish.jersey.media:jersey-media-json-binding:3.1.0-M7")

}

application {
    // Define the main class for the application.
    mainClass.set("github.souchy.ankama.quickfus.Quickfus")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
