# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Aurelia CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
defaults:
  run:
    working-directory: './DofusBuilder Frontend/'
    
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'# Set always-auth in npmrc.
        cache-dependency-path: './DofusBuilder Frontend/package-lock.json'
    #- run: npm ci
    #- run: npm run build --if-present
    #- run: npm test
    - run: npm install
    - name: Setup aurelia 
      run: |
        npm install aurelia-cli -g
        au build

  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.ftp_url }}
        username: ${{ secrets.ftp_user }}
        password: ${{ secrets.ftp_pass }}
        protocol: ftps
        port: 22
        server-dir: '/var/www/html/quickfus.ddns.net/'
        local-dir: './DofusBuilder Frontend/'
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/aurelia_project/**
          package.json
          package-lock.json
          README.md
          tsconfig.json
          tslint.json
          .editorconfig
          favicon.ico
          
        
      
