# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Aurelia CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
defaults:
  run:
    working-directory: './DofusBuilder Frontend/'
    
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'# Set always-auth in npmrc.
        cache-dependency-path: './DofusBuilder Frontend/package-lock.json'
    #- run: npm ci
    #- run: npm run build --if-present
    #- run: npm test
    - run: npm install
    - name: Setup aurelia 
      run: |
        npm install aurelia-cli -g
        au build
  
  upload_files:
    needs: build
    runs-on: ubuntu-latest
    name: Upload a builded file.
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    
    - run: pwd
    - run: cd "/home/runner/work/quickfus/quickfus/DofusBuilder Frontend"
    - run: ls
    
    - name: Upload Files
      id: upload
      uses: Creepios/sftp-action@v1.0.3
      with:
        port: 22
        host: ${{ secrets.ftp_url }}
        username: ${{ secrets.ftp_user }}
        password: ${{ secrets.ftp_pass }}
        remotePath: '/var/www/html/quickfus.ddns.net/src'
        localPath: 'src/'
        additionalPaths: '{"/home/runner/work/quickfus/quickfus/DofusBuilder Frontend/scripts":"/var/www/html/quickfus.ddns.net/scripts/"}'

